### ISSUE TITLE
Подключение модуля

### ISSUE THREAD

**Issue by 433920** [alexander-sholohov/si4463-beacon#2]
Александр, интересный проект! По si4463 крайне мало информации для моего начального уровня. Поэтому внимательно изучаю Ваш код и схему для апгрейда своего проекта на простых трехпиновых модулях приема и передачи в более мощный si4463. Не могу понять, для чего в Вашей схеме задействуется пин GPIO0, если передача информации просходит через пины MISO/MOSI? Или эти пины активируют приемник/передатчик? В таком случае зачем подключены они оба, если проект не предусматривает прием?

**Comment by alexander-sholohov** [comment]
Модуль работает только на передачу, в проекте приема нет. Модуляция - on-off keying с управлением через GPIO0 
"1" - идет несущая в эфир, "0" - нет.
Вот [тут](https://github.com/alexander-sholohov/si4463-beacon/tree/master/doc/WDS) шаги настройке в программе от SiLabs.
